CREATE TABLE [dbo].[User]
(
	[UserId] BIGINT NOT NULL IDENTITY,
	[UserName] NVARCHAR(MAX) NOT NULL,
	[UserGlobalidentity] UNIQUEIDENTIFIER NOT NULL,
	[CreatedDateTiime] DATETIME NOT NULL,
	[UserTypeEnum] INT NOT NULL,
	[IsActive] BIT NOT NULL DEFAULT 0,
	[IsSuspend] BIT NOT NULL DEFAULT 0,
	[LastOtpSequence] INT NULL,
	[LastOtpSequencedateTime] DATETIME NULL,
	[PhoneNo] NVARCHAR(100) NULL,

	CONSTRAINT [PK_User_UserId] PRIMARY KEY CLUSTERED ([UserId])
)
